### ISSUE TITLE
nvim-treesitter command not available

### ISSUE THREAD

**Issue by datfooldive** [martin-braun/CocChad#1]
i found this configuration and its really help me
but i have issue with treesitter

its not available/disable but in config its already setup

![Screenshot_20240105-215103.png](https://github.com/martin-braun/CocChad/assets/110718021/41fde302-2be0-4ac7-8438-0735a637aafc)

how to use/enable nvim-treesitter because i cant use TSInstall😔

**Comment by martin-braun** [comment]
NvChad uses `treesitter` and some other plugins that are very common. However, I decided to disable them in favor of `coc.nvim`. This is an alternative solution for LSP or code suggestion stuff. It uses nodeJS under the hood and allows to run plugins that are forked from VSCode plugins, hence the plugins provide an easier entry, since they often come with LSP calls, commands and snippets in one package. My configuration expects you to alias the `lts` version of `node` via `nvm`.

It's expected that these plugins are disabled:

```
  Disabled (13)
     cmp-buffer 
     cmp-nvim-lsp 
     cmp-nvim-lua 
     cmp-path 
     cmp_luasnip 
     friendly-snippets 
     LuaSnip 
     mason.nvim 
     nvim-autopairs 
     nvim-cmp 
     nvim-lspconfig 
     nvim-treesitter  telescope.nvim 
     nvterm 
```

`cmp`, `lspconfig`, `mason`, `friendly-snippets` and `treesitter` are all replaced by `coc.nvim`. The `coc.nvim` plugins are defined at https://github.com/martin-braun/CocChad/blob/v2.0/lua/custom/chad/plugins.lua#L27

`nvterm` is disabled, because I use `tmux` as a wrapper. 

If you fork from my configuration you can change all that by editing this file: https://github.com/martin-braun/CocChad/blob/v2.0/lua/custom/chad/specs/_stock.lua#L45 (highlighted treesitter line)

However, I advice you to not use my configuration, if you want to use NvChad as its intended. I kinda break out of their template to use `coc.nvim` which makes my life easier, but comes at the cost of having a `node` dependency and a lot of disabled plugins from NvChad.

**Comment by datfooldive** [comment]
go it. thanks :)
